# Generated by Django 5.0.2 on 2024-02-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=5)),
                ('photo', models.ImageField(default='prod.jpg', upload_to='product_image')),
                ('cost', models.IntegerField(blank=True)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
